-- Script generated by SimpleSpy - credits to exx#9394
shared.go = not shared.go
local module = require(game:GetService("ReplicatedStorage").Items.Pets.Module)
while shared.go and task.wait() do
local args = {
    [1] = 5,
    [2] = false
}

game:GetService("ReplicatedStorage").Network.ToServer.Requests.OpenPetCrate:FireServer(unpack(args))

local t = {}
for _, v in pairs(game:GetService("Players").LocalPlayer.Inventory.Pets:GetChildren()) do
    if module.GetItemByID(v.Name) then
        local rarity = module.GetItemByID(v.Name).Info.Rarity.Value
        if rarity == 2 or rarity == 3 or rarity == 4 then
            table.insert(t, v)
        end
    end
end
game:GetService("ReplicatedStorage").Network.ToServer.Requests.DeletePets:FireServer(t)

end